# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrbitBooks', '0003_auto_20180906_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrbitBooks.Genre'),
        ),
    ]
