# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrbitBooks', '0004_auto_20180906_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrbitBooks.GroupGenre'),
        ),
    ]
