# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrbitBooks', '0007_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrbitBooks.Country'),
        ),
    ]
